Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2018-04, with the labels that each got.

#822 Entities with construct can be used on Collection and AdminType
  src/Builder/FormContractor.php
  tests/Builder/FormContractorTest.php
Labels: patch

#828 Fixed a typo on doctrine_orm_number
  docs/reference/filter_field_definition.rst
Labels: docs

#827 #473. Available disable distinct for ProxyQuery and Pager.
  docs/reference/query_proxy.rst
  src/Datagrid/Pager.php
  src/Datagrid/ProxyQuery.php
  tests/Datagrid/PagerTest.php
  tests/Datagrid/ProxyQueryTest.php
Labels: minor
