Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2019-11, with the labels that each got.

#949 Avoid exception when no result
  src/Datagrid/Pager.php
  tests/Datagrid/PagerTest.php
Labels: patch

#950 allow DoctrineBundle 2.0
  composer.json
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: minor

#954 Steal fixture from the Doctrine bridge
  tests/Datagrid/ProxyQueryTest.php
  tests/Fixtures/Entity/DoubleNameEntity.php
Labels: critical, pedantic

#952 Fix ProxyQuery::getQueryBuilder() return type
  src/Datagrid/ProxyQuery.php
Labels: patch

#955 Allow to override Operator option
  src/Filter/BooleanFilter.php
  src/Filter/ChoiceFilter.php
  src/Filter/ClassFilter.php
  tests/Filter/BooleanFilterTest.php
  tests/Filter/CallbackFilterTest.php
  tests/Filter/ChoiceFilterTest.php
  tests/Filter/ClassFilterTest.php
Labels: minor
