Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2019-01, with the labels that each got.

#879 Remove useless backslash
  src/DependencyInjection/Configuration.php
  src/Model/ModelManager.php
Labels: critical, pedantic

#884 Allow exporter 2
  composer.json
  src/Model/ModelManager.php
Labels: minor

#885 [Docs] big cleanup
  docs/reference/audit.rst
  docs/reference/filter_field_definition.rst
  docs/reference/form_field_definition.rst
  docs/reference/form_types_and_transformers.rst
  docs/reference/installation.rst
  docs/reference/list_field_definition.rst
  docs/reference/query_proxy.rst
  docs/reference/templates.rst
  docs/reference/troubleshootings.rst
  docs/tutorial/creating_your_first_admin_class/defining_admin_class.rst
  docs/tutorial/creating_your_first_admin_class/defining_crud_controller.rst
  docs/tutorial/creating_your_first_admin_class/defining_entities.rst
Labels: docs

#891 include string cast to avoid typeError with explode function
  src/Model/ModelManager.php
Labels: patch
