Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2020-07, with the labels that each got.

#979 Add new filter for empty fields
  docs/reference/filter_field_definition.rst
  src/Filter/EmptyFilter.php
  src/Resources/config/doctrine_orm_filter_types.xml
  tests/Filter/EmptyFilterTest.php
Labels: feature, minor

#1067 Prepare support for BlockBundle 4
  src/Block/AuditBlockService.php
  src/Resources/config/audit.xml
  tests/Block/AuditBlockServiceTest.php
  tests/Block/DeprecatedAuditBlockServiceTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php
Labels: minor

#1069 Improve deprecation messages for AuditBlockService
  src/Block/AuditBlockService.php
Labels: pedantic

#1070 Add typehint for private methods and improve tests
  src/Builder/FormContractor.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/DependencyInjection/Compiler/AddAuditEntityCompilerPass.php
  src/Filter/AbstractDateFilter.php
  src/Filter/ClassFilter.php
  src/Filter/ModelFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
Labels: pedantic

#1061 Add deprecation for StringFilter format option
  UPGRADE-3.x.md
  src/Filter/StringFilter.php
  tests/Filter/StringFilterTest.php
Labels: minor

#1075 Prepare release 3.21
  CHANGELOG.md
  UPGRADE-3.x.md
  src/Block/AuditBlockService.php
  src/Filter/StringFilter.php
  tests/Block/DeprecatedAuditBlockServiceTest.php
  tests/Filter/StringFilterTest.php
Labels: pedantic

#1077 Use deprecated tag instead of sonata_template_deprecate
  composer.json
  src/Resources/views/CRUD/edit_modal.html.twig
  src/Resources/views/CRUD/edit_orm_many_association_script.html.twig
  src/Resources/views/CRUD/edit_orm_many_to_many.html.twig
  src/Resources/views/CRUD/edit_orm_many_to_one.html.twig
  src/Resources/views/CRUD/edit_orm_one_association_script.html.twig
  src/Resources/views/CRUD/edit_orm_one_to_many.html.twig
  src/Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig
  src/Resources/views/CRUD/edit_orm_one_to_many_inline_tabs.html.twig
  src/Resources/views/CRUD/edit_orm_one_to_many_sortable_script_table.html.twig
  src/Resources/views/CRUD/edit_orm_one_to_many_sortable_script_tabs.html.twig
  src/Resources/views/CRUD/edit_orm_one_to_one.html.twig
  src/Resources/views/CRUD/list_orm_many_to_many.html.twig
  src/Resources/views/CRUD/list_orm_many_to_one.html.twig
  src/Resources/views/CRUD/list_orm_one_to_many.html.twig
  src/Resources/views/CRUD/list_orm_one_to_one.html.twig
  src/Resources/views/CRUD/show_orm_many_to_many.html.twig
  src/Resources/views/CRUD/show_orm_many_to_one.html.twig
  src/Resources/views/CRUD/show_orm_one_to_many.html.twig
  src/Resources/views/CRUD/show_orm_one_to_one.html.twig
Labels: patch

#1078 Use propertyAccessor and deprecate camelize
  UPGRADE-3.x.md
  composer.json
  src/Model/ModelManager.php
  src/Resources/config/doctrine_orm.xml
  tests/Model/ModelManagerTest.php
Labels: minor
