Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2020-10, with the labels that each got.

#1141 Fix phpstan build
  composer.json
  phpstan-baseline.neon
Labels: pedantic

#1140 Replace prophesize with regular phpunit mocks
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
  tests/DependencyInjection/Compiler/AddGuesserCompilerPassTest.php
  tests/Guesser/FilterTypeGuesserTest.php
  tests/Guesser/TypeGuesserTest.php
  tests/Model/AuditReaderTest.php
  tests/SonataDoctrineORMAdminBundleTest.php
Labels: hacktoberfest, pedantic

#1142 Pass option by_reference in case we're using AdminType
  src/Builder/FormContractor.php
  tests/Builder/FormContractorTest.php
Labels: minor

#1151 Prepare 3.24 release
  CHANGELOG.md
  src/Admin/FieldDescription.php
  src/Builder/DatagridBuilder.php
  src/Builder/FormContractor.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/Datagrid/Pager.php
  src/DependencyInjection/Compiler/AddAuditEntityCompilerPass.php
  src/DependencyInjection/Compiler/AddGuesserCompilerPass.php
  src/DependencyInjection/Compiler/AddTemplatesCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataDoctrineORMAdminExtension.php
  src/Filter/BooleanFilter.php
  src/Filter/CallbackFilter.php
  src/Filter/ChoiceFilter.php
  src/Filter/ClassFilter.php
  src/Filter/DateFilter.php
  src/Filter/DateRangeFilter.php
  src/Filter/DateTimeFilter.php
  src/Filter/DateTimeRangeFilter.php
  src/Filter/ModelAutocompleteFilter.php
  src/Filter/ModelFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
  src/Filter/TimeFilter.php
  src/Guesser/FilterTypeGuesser.php
  src/Guesser/TypeGuesser.php
  src/Model/AuditReader.php
  src/Model/ModelManager.php
  src/SonataDoctrineORMAdminBundle.php
  src/Util/ObjectAclManipulator.php
Labels: pedantic

#1159 Add deprecation if callback return type is not a boolean
  UPGRADE-3.x.md
  docs/reference/filter_field_definition.rst
  src/Filter/CallbackFilter.php
  tests/Filter/CallbackFilterTest.php
Labels: minor

#1166 Throw exception if array passed as argument 3 to `ModelManager::addIdentifiersToQuery()` is empty
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: minor

#1136 Cast the value as string before calling `explode()` at `ModelManager::addIdentifiersToQuery()`
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: patch

#1169 Add compatibility with Symfony 5
  composer.json
Labels: major

#1171 fix compatibility with SonataAdminBundle 4
  src/Builder/FormContractor.php
  src/Guesser/FilterTypeGuesser.php
  src/Guesser/TypeGuesser.php
  tests/Guesser/FilterTypeGuesserTest.php
Labels: major

#1170 Remove fieldDescription deprecation
  composer.json
  src/Admin/FieldDescription.php
  src/Model/ModelManager.php
  tests/Admin/FieldDescriptionTest.php
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
  tests/Model/ModelManagerTest.php
Labels: patch
