Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2020-03, with the labels that each got.

#990 Address PHPUnit's warnings
  tests/Block/AuditBlockServiceTest.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: pedantic

#1001 Add support for simple_array type to TypeGuesser
  src/Guesser/TypeGuesser.php
  tests/Guesser/TypeGuesserTest.php
Labels: minor

#997 use SortBy before custom orderBy
  src/Datagrid/ProxyQuery.php
  tests/Datagrid/ProxyQueryTest.php
Labels: patch

#998 Handle case without sort_by value
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: minor

#999 allow null selection in ChoiceFilter
  src/Filter/ChoiceFilter.php
  tests/Filter/ChoiceFilterTest.php
  tests/Filter/QueryBuilder.php
Labels: minor

#1006 Fix missing prepending extension
  tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php
Labels: pedantic

#1000 Make notIn and In function consistent
  tests/Filter/BooleanFilterTest.php
  tests/Filter/ChoiceFilterTest.php
  tests/Filter/ModelFilterTest.php
  tests/Filter/QueryBuilder.php
  tests/Filter/StringFilterTest.php
Labels: minor

#992 Replace deprecated constant
  src/Filter/AbstractDateFilter.php
  src/Filter/ChoiceFilter.php
  src/Filter/ClassFilter.php
  src/Filter/ModelAutocompleteFilter.php
  src/Filter/ModelFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
  src/Guesser/FilterTypeGuesser.php
  tests/Filter/ChoiceFilterTest.php
  tests/Filter/ClassFilterTest.php
  tests/Filter/ModelFilterTest.php
  tests/Filter/NumberFilterTest.php
  tests/Filter/StringFilterTest.php
  tests/Guesser/FilterTypeGuesserTest.php
Labels: patch

#1007 Revert "Fix missing prepending extension"
  tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php
Labels: pedantic

#1011 Remove choice filter 'all' special case
  src/Filter/ChoiceFilter.php
  tests/Filter/ChoiceFilterTest.php
Labels: major

#1013 Fix deprecation
  src/Filter/AbstractDateFilter.php
Labels: patch

#1004 Stop using default _sort_by
  src/Model/ModelManager.php
Labels: major

#1017 Update admin version
  composer.json
Labels: minor, vendor

#996 Concat value of complex primary key for correct calculate total pages in Datagrid
  src/Datagrid/Pager.php
  tests/Datagrid/PagerTest.php
  tests/Fixtures/Entity/ORM/User.php
  tests/Fixtures/Entity/ORM/UserBrowser.php
Labels: patch

#1018 Add method annotation for ProxyQuery
  src/Datagrid/ProxyQuery.php
Labels: minor

#1020 Save extra processing at `Pager::countCompositePrimaryKey()`
  src/Datagrid/Pager.php
Labels: pedantic

#1022 Drop support of php 7.1
  composer.json
Labels: Needs: Upgrade note, minor
