Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2020-11, with the labels that each got.

#1186 Remove useless anotation legacy
  tests/Block/AuditBlockServiceTest.php
Labels: pedantic

#1189 Fix date handling through `DateRangeFilter`
  src/Filter/AbstractDateFilter.php
  tests/Filter/DateRangeFilterTest.php
Labels: patch

#1190 Add support for `\DateTimeImmutable` at `AbstractDateFilter::filter()`
  src/Filter/AbstractDateFilter.php
  tests/Filter/DateRangeFilterTest.php
Labels: minor

#1191 Add Next major comment related to https://github.com/sonata-project/SonataAdminBundle/pull/6578
  src/Builder/DatagridBuilder.php
Labels: pedantic

#1196 Add upgrade note for #1190
  UPGRADE-3.x.md
Labels: pedantic

#1197 Pass collection_by_reference instead of by_reference
  composer.json
  src/Builder/FormContractor.php
  tests/Builder/FormContractorTest.php
Labels: patch

#1202 Add NOT_EQUAL support for StringFilter
  composer.json
  src/Filter/StringFilter.php
  tests/Filter/StringFilterTest.php
Labels: minor

#1198 Use correctly phpstan-symfony
  composer.json
Labels: pedantic

#1120 Allow empty string for filtering
  docs/reference/filter_field_definition.rst
  src/Filter/StringFilter.php
  tests/Filter/StringFilterTest.php
Labels: minor

#1212 Add DataSource
  src/Exporter/DataSource.php
  src/Resources/config/doctrine_orm.xml
  tests/Exporter/DataSourceTest.php
Labels: minor
