Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2020-08, with the labels that each got.

#1084 Remove sonata_help block
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: major

#1086 Remove references to deprecated help option
  docs/reference/form_field_definition.rst
  tests/Admin/FieldDescriptionTest.php
Labels: pedantic

#1023 Add support for SonataBlockBundle 4.x
  UPGRADE-3.x.md
  composer.json
  src/Block/AuditBlockService.php
Labels: minor

#1098 Fix block related tests
  tests/Block/AuditBlockServiceTest.php
  tests/Block/DeprecatedAuditBlockServiceTest.php
Labels: pedantic

#1091 Allow some symfony/* dependencies to use version ^5.1
  composer.json
Labels: minor
