Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2020-06, with the labels that each got.

#1060 Fix test after drop CoreBundle
  tests/Builder/FormContractorTest.php
Labels: patch

#1049 Add some deprecations about invalid values
  UPGRADE-3.x.md
  src/Admin/FieldDescription.php
  src/Builder/DatagridBuilder.php
  src/Builder/FormContractor.php
  src/Model/ModelManager.php
  tests/Admin/FieldDescriptionTest.php
  tests/Builder/FormContractorTest.php
  tests/Model/ModelManagerTest.php
Labels: Needs: Upgrade note, minor

#1057 Add StringFilter support for START_WITH and END_WITH operator
  composer.json
  src/Filter/StringFilter.php
  tests/Filter/StringFilterTest.php
Labels: minor

#1064 Replace "3.x" with the corresponding release versions
  UPGRADE-3.x.md
Labels: docs, pedantic
