Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2020-04, with the labels that each got.

#1024 Add explicit `null` return values at `ModelManager::getNormalizedIdentifier()`
  src/Model/ModelManager.php
Labels: patch

#1027 Deprecate getModelIdentifier
  src/Model/ModelManager.php
Labels: minor

#1028 Fix a link to Doctrine documentation site
  src/Admin/FieldDescription.php
Labels: pedantic

#1030 Fix type check at `ModelManager::getNormalizedIdentifier()`
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: patch

#1032 Fix camel case for `ModelManager::getUrlSafeIdentifier()` method
  src/Model/ModelManager.php
Labels: pedantic

#1036 Fix typos
  CONTRIBUTING.md
  docs/reference/audit.rst
  tests/Admin/FieldDescriptionTest.php
Labels: docs, pedantic
