Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2021-02, with the labels that each got.

#1292 Close API
  src/Datagrid/ProxyQuery.php
  src/Exporter/DataSource.php
Labels: minor

#1290 Remove useless code
  src/Filter/AbstractDateFilter.php
Labels: major

#1293 Add Typehint
  src/Admin/FieldDescription.php
  src/Datagrid/OrderByToSelectWalker.php
  src/Datagrid/ProxyQuery.php
  src/Datagrid/ProxyQueryInterface.php
  src/DependencyInjection/Compiler/AddTemplatesCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/Filter/AbstractDateFilter.php
  src/Filter/BooleanFilter.php
  src/Filter/CallbackFilter.php
  src/Filter/ChoiceFilter.php
  src/Filter/ClassFilter.php
  src/Filter/EmptyFilter.php
  src/Filter/Filter.php
  src/Filter/ModelAutocompleteFilter.php
  src/Filter/ModelFilter.php
  src/Filter/NullFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
  src/Filter/StringListFilter.php
  src/Guesser/AbstractTypeGuesser.php
  tests/Filter/BooleanFilterTest.php
  tests/Filter/CallbackFilterTest.php
  tests/Filter/ChoiceFilterTest.php
  tests/Filter/ClassFilterTest.php
  tests/Filter/DateFilterTest.php
  tests/Filter/DateRangeFilterTest.php
  tests/Filter/DateTimeFilterTest.php
  tests/Filter/DateTimeRangeFilterTest.php
  tests/Filter/EmptyFilterTest.php
  tests/Filter/ModelFilterTest.php
  tests/Filter/NullFilterTest.php
  tests/Filter/NumberFilterTest.php
  tests/Filter/StringFilterTest.php
  tests/Filter/StringListFilterTest.php
  tests/Filter/TimeFilterTest.php
Labels: major

#1287 Fix countFilter condition
  src/Filter/CountFilter.php
  tests/Filter/BooleanFilterTest.php
  tests/Filter/CallbackFilterTest.php
  tests/Filter/ChoiceFilterTest.php
  tests/Filter/ClassFilterTest.php
  tests/Filter/CountFilterTest.php
  tests/Filter/DateRangeFilterTest.php
  tests/Filter/EmptyFilterTest.php
  tests/Filter/FilterTestCase.php
  tests/Filter/ModelFilterTest.php
  tests/Filter/NullFilterTest.php
  tests/Filter/NumberFilterTest.php
  tests/Filter/StringFilterTest.php
  tests/Filter/StringListFilterTest.php
Labels: patch

#1295 close API: make classes final
  src/Admin/FieldDescription.php
  src/Block/AuditBlockService.php
  src/Builder/DatagridBuilder.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/Datagrid/Pager.php
  src/DependencyInjection/Compiler/AddAuditEntityCompilerPass.php
  src/DependencyInjection/Compiler/AddGuesserCompilerPass.php
  src/DependencyInjection/Compiler/AddTemplatesCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataDoctrineORMAdminExtension.php
  src/Filter/BooleanFilter.php
  src/Filter/CallbackFilter.php
  src/Filter/ChoiceFilter.php
  src/Filter/ClassFilter.php
  src/Filter/DateFilter.php
  src/Filter/DateRangeFilter.php
  src/Filter/DateTimeFilter.php
  src/Model/ModelManager.php
  src/SonataDoctrineORMAdminBundle.php
  src/Util/ObjectAclManipulator.php
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
  tests/Guesser/FilterTypeGuesserTest.php
  tests/Guesser/TypeGuesserTest.php
  tests/Model/ModelManagerTest.php
Labels: major

#1291 Deprecate passing a non integer or non existing type
  src/Filter/AbstractDateFilter.php
  src/Filter/ClassFilter.php
  src/Filter/CountFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
Labels: minor

#1288 Add next major comment
  src/Builder/DatagridBuilder.php
Labels: pedantic

#1301 make remaining classes final
  src/Datagrid/ProxyQuery.php
  src/Exporter/DataSource.php
  src/Filter/DateTimeRangeFilter.php
  src/Filter/ModelAutocompleteFilter.php
  src/Filter/ModelFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
  src/Filter/TimeFilter.php
  src/Guesser/FilterTypeGuesser.php
  src/Guesser/TypeGuesser.php
  src/Model/AuditReader.php
  src/Model/ModelManager.php
  tests/Datagrid/ProxyQueryTest.php
  tests/Exporter/DataSourceTest.php
  tests/Model/ModelManagerTest.php
Labels: major

#1247 Handle null when using NOT_EQUALS with ChoiceFilter
  src/Filter/ChoiceFilter.php
  tests/Filter/ChoiceFilterTest.php
  tests/Filter/ModelFilterTest.php
Labels: patch

#1308 fix compatiblity with latest SonataAdminBundle changes
  tests/Admin/FieldDescriptionTest.php
Labels: major

#1309 remove NEXT_MAJOR comments
  src/Builder/DatagridBuilder.php
  src/Filter/AbstractDateFilter.php
  src/Filter/CallbackFilter.php
  src/Filter/ClassFilter.php
  src/Filter/CountFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
  src/Model/ModelManager.php
  tests/Filter/CallbackFilterTest.php
  tests/Filter/StringFilterTest.php
  tests/Model/ModelManagerTest.php
Labels: major

#1285 Allow php 8.0
  .github/workflows/test.yaml
  composer.json
Labels: minor
