Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2021-03, with the labels that each got.

#1323 Avoid calling a non existant method
  src/Resources/config/security.xml
  src/Util/ObjectAclManipulator.php
Labels: minor

#1321 Improve phpdoc
  src/Filter/Filter.php
Labels: pedantic

#1322 Re-add getUniqueParameterId and entityJoin
  src/Datagrid/ProxyQueryInterface.php
Labels: major

#1327 Set default field_name value in DatagridBuilder
  src/Builder/DatagridBuilder.php
  tests/Builder/DatagridBuilderTest.php
Labels: major

#1329 Allow null type
  src/Filter/Filter.php
Labels: pedantic

#1332 Fix some static analysis errors
  src/Builder/FormContractor.php
  src/Model/ModelManager.php
  tests/Builder/FormContractorTest.php
Labels: pedantic

#1333 Deprecate passing arguments to execute method
  src/Datagrid/ProxyQuery.php
Labels: minor

#1334 Deprecate passing arguments to `ProxyQuery::execute()`, regardless its values
  src/Datagrid/ProxyQuery.php
Labels: pedantic

#1336 Address some direct deprecations from tests
  composer.json
  tests/Admin/FieldDescriptionTest.php
Labels: minor

#1335 Update constraints in order to allow some "symfony/*:^5.2" deps
  composer.json
Labels: dependencies, minor

#1337 Remove next_major comment
  tests/Admin/FieldDescriptionTest.php
Labels: pedantic

#1349 make AuditBlockService::$auditReader private
  src/Block/AuditBlockService.php
Labels: major

#1350 Add FieldDescriptionFactory
  composer.json
  src/Builder/DatagridBuilder.php
  src/Builder/FormContractor.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/FieldDescription/FieldDescriptionFactory.php
  src/Guesser/AbstractTypeGuesser.php
  src/Guesser/FilterTypeGuesser.php
  src/Guesser/TypeGuesser.php
  src/Model/ModelManager.php
  src/Resources/config/doctrine_orm.xml
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
  tests/Guesser/FilterTypeGuesserTest.php
  tests/Guesser/TypeGuesserTest.php
  tests/Model/ModelManagerTest.php
Labels: minor

#1355 Add reverseTransform
  UPGRADE-3.x.md
  composer.json
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: minor

#1357 Fix next major and phpstan issues
  phpstan.neon.dist
  src/Builder/DatagridBuilder.php
  src/Builder/FormContractor.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/Datagrid/Pager.php
  src/Datagrid/ProxyQuery.php
  src/DependencyInjection/Configuration.php
  src/FieldDescription/FieldDescriptionFactory.php
  src/Filter/ChoiceFilter.php
  src/Model/ModelManager.php
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/ListBuilderTest.php
  tests/Model/ModelManagerTest.php
Labels: major

#1364 Update `FilterTest`
  tests/Filter/FilterTest.php
Labels: pedantic

#1365 Fix missing argument 2 for `trigger_error()`
  src/Datagrid/Pager.php
  src/Exporter/DataSource.php
  src/Filter/AbstractDateFilter.php
  src/Filter/Filter.php
  src/Filter/ModelAutocompleteFilter.php
  src/Filter/ModelFilter.php
  src/Filter/StringFilter.php
Labels: patch

#1358 Fix filter query when using "OR" conditions
  src/Filter/Filter.php
  tests/Filter/FilterTest.php
Labels: patch

#1372 Fix CI
  composer.json
  src/Admin/FieldDescription.php
  src/Builder/DatagridBuilder.php
  src/Builder/FormContractor.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/FieldDescription/FieldDescriptionFactory.php
  src/Guesser/FilterTypeGuesser.php
  src/Guesser/TypeGuesser.php
  src/Model/ModelManager.php
  tests/Admin/FieldDescriptionTest.php
  tests/App/Admin/AuthorAdmin.php
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/ShowBuilderTest.php
  tests/Guesser/FilterTypeGuesserTest.php
  tests/Guesser/TypeGuesserTest.php
  tests/Model/ModelManagerTest.php
Labels: pedantic

#1378 Use FieldDescription namespace instead of Guesser
  src/Resources/config/doctrine_orm.xml
Labels: pedantic

#1379 Prepare 3.32
  UPGRADE-3.x.md
  src/Builder/ListBuilder.php
  src/Datagrid/ProxyQuery.php
  src/DependencyInjection/SonataDoctrineORMAdminExtension.php
  src/Guesser/AbstractTypeGuesser.php
  src/Guesser/FilterTypeGuesser.php
  src/Guesser/TypeGuesser.php
  src/Model/ModelManager.php
Labels: pedantic
