Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2021-01, with the labels that each got.

#1232 Stop using deprecated FieldDescription methods
  composer.json
  src/Admin/FieldDescription.php
  src/Builder/DatagridBuilder.php
  src/Builder/FormContractor.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/Model/ModelManager.php
  tests/Admin/FieldDescriptionTest.php
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/FormContractorTest.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
  tests/Model/ModelManagerTest.php
Labels: minor

#1211 Add deprecation for method removed from the interface
  UPGRADE-3.x.md
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: minor

#1242 Add functional tests
  composer.json
  phpunit.xml.dist
  tests/App/Admin/AuthorAdmin.php
  tests/App/Admin/BookAdmin.php
  tests/App/Admin/CategoryAdmin.php
  tests/App/AppKernel.php
  tests/App/DataFixtures/AppFixtures.php
  tests/App/Entity/Address.php
  tests/App/Entity/Author.php
  tests/App/Entity/Book.php
  tests/App/Entity/Category.php
  tests/App/config/config.yml
  tests/App/config/routes.yaml
  tests/App/config/security.yml
  tests/App/config/services.php
  tests/App/public/index.php
  tests/Functional/BasePantherTestCase.php
  tests/Functional/CRUDTest.php
  tests/Functional/EmbeddedMappingTest.php
  tests/Functional/ManyToOneMappingTest.php
  tests/bootstrap.php
  tests/custom_bootstrap.php
Labels: pedantic

#1256 Fix param name in doc
  docs/reference/filter_field_definition.rst
Labels: pedantic

#1254 Delete button is independent of the ability to delete an object
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#1258 [Tests] Split fixtures into files
  tests/App/DataFixtures/AuthorFixtures.php
  tests/App/DataFixtures/BookFixtures.php
  tests/App/DataFixtures/CategoryFixtures.php
  tests/App/config/services.php
  tests/Functional/CRUDTest.php
  tests/Functional/EmbeddedMappingTest.php
  tests/Functional/ManyToOneMappingTest.php
Labels: pedantic

#1273 Bump symfony/panther to 0.9
  composer.json
Labels: pedantic

#1283 Stop using deprecated constants
  src/Guesser/TypeGuesser.php
  tests/Builder/ShowBuilderTest.php
Labels: pedantic

#1280 create CountFilter
  docs/reference/filter_field_definition.rst
  src/Filter/CountFilter.php
  src/Filter/Filter.php
  tests/Filter/CountFilterTest.php
  tests/Filter/FilterTestCase.php
Labels: minor

#1289 Fix tests
  src/Builder/DatagridBuilder.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/Filter/AbstractDateFilter.php
Labels: major
