Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2021-04, with the labels that each got.

#1388 Remove extra argument separator in `sprintf()` calls at `ProxyQuery`
  src/Datagrid/ProxyQuery.php
Labels: pedantic

#1394 Fix declaration of filters
  src/Resources/config/doctrine_orm_filter_types.xml
Labels: pedantic

#1391 Test on different platforms
  .github/workflows/test-platforms.yaml
  tests/App/config/config.yml
Labels: pedantic

#1399 Avoid always triggering deprecation
  src/Model/ModelManager.php
Labels: patch

#1401 Make property public
  tests/App/Admin/SubAdmin.php
  tests/App/Entity/Sub.php
Labels: pedantic

#1395 Use "BINARY()" DQL function for case sensitive MySQL pattern matching in `StringFilter::filter()`
  UPGRADE-3.x.md
  composer.json
  docs/reference/filter_field_definition.rst
  src/Filter/StringFilter.php
  src/Resources/config/doctrine_orm_filter_types.xml
  tests/Filter/FilterTest.php
  tests/Filter/StringFilterTest.php
Labels: minor

#1409 Fix Revision instantiation
  tests/Block/AuditBlockServiceTest.php
Labels: pedantic

#1412 Do not restrict to alpha-1
  composer.json
Labels: major

#1414 Fix return type for `ModelManager::getModelIdentifier()`
  src/Model/ModelManager.php
Labels: patch

#1418 Add stability alpha to sonata-project/admin-bundle
  composer.json
Labels: pedantic

#1419 add more specific phpdoc
  src/Filter/Filter.php
Labels: pedantic

#1423 documentation for custom DataSource
  docs/index.rst
  docs/reference/data_source.rst
Labels: docs
