Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2021-05, with the labels that each got.

#1428 Add forward compatibility with FilterData
  UPGRADE-3.x.md
  src/Filter/CallbackFilter.php
  tests/Filter/CallbackFilterTest.php
  tests/Fixtures/Util/CallbackClass.php
Labels: minor

#1435 Fix batchDelete
  src/Model/ModelManager.php
  src/Util/ObjectAclManipulator.php
Labels: patch

#1440 3.x into Master
  CHANGELOG.md
  UPGRADE-3.x.md
Labels: pedantic

#1439 Fix binding arbitrary params as part of a value expression in the query filter at `Filter::applyWhere()` with PostgreSQL
  src/Filter/Filter.php
  tests/App/Admin/BookWithAuthorAutocompleteAdmin.php
  tests/App/config/services.php
  tests/Filter/FilterTest.php
  tests/Functional/RetrieveAutocompleteItemsActionTest.php
Labels: patch

#1445 Bump psalm level 3
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
  src/DependencyInjection/Configuration.php
Labels: pedantic
