Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2021-11, with the labels that each got.

#1562 Add support for Symfony 6
  .github/workflows/test.yaml
  composer.json
  phpunit.xml.dist
  tests/Functional/BasePantherTestCase.php
Labels: minor

#1577 Fix psalm
  src/Exporter/DataSource.php
Labels: pedantic

#1571 Fix merge direction
  src/Builder/DatagridBuilder.php
Labels: patch

#1584 Symfony Panther 2.0 supports Symfony 6
  .github/workflows/test.yaml
  composer.json
  phpunit.xml.dist
  tests/Functional/BasePantherTestCase.php
Labels: pedantic

#1585 Paginator with useOutputWalkers=false allows query with joins (#1583) (Backport commit from 4.x to 3.x)
  src/Util/SmartPaginatorFactory.php
  tests/Util/SmartPaginatorFactoryTest.php
Labels: bug
