Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2022-01, with the labels that each got.

#1615 Fix phpstan issues
  psalm-baseline.xml
  src/Model/ModelManager.php
Labels: pedantic

#1616 Fix detection of output walkers in pagination
  src/Util/SmartPaginatorFactory.php
  tests/App/Entity/ProductAttribute.php
  tests/Util/SmartPaginatorFactoryTest.php
Labels: patch

#1618 Fix phpstan build
  src/Datagrid/ProxyQuery.php
Labels: pedantic

#1599 Added example for JsonListFilter
  docs/reference/filter_field_definition.rst
Labels: docs

#1622 Remove list field definition
  docs/index.rst
  docs/reference/list_field_definition.rst
Labels: docs

#1623 Fix detection of use of output walkers in pagination (#1616) (Backport commit from 4.x to 3.x)
  src/Util/SmartPaginatorFactory.php
  tests/App/Entity/ProductAttribute.php
  tests/Util/SmartPaginatorFactoryTest.php
Labels: patch
