Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2023-05, with the labels that each got.

#1752 Up rector to 0.16
  composer.json
Labels: pedantic

#1753 DevKit updates for 4.x branch
  .github/workflows/test.yaml
Labels: minor

#1755 Add support for form-extensions 2.0
  composer.json
Labels: minor

#1756 Release 4.13.0
  CHANGELOG.md
Labels: dev-kit
