Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2023-04, with the labels that each got.

#1733 Make getRealClass more robust
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: pedantic

#1734 Improve exception message at `ModelManager::batchDelete()`
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: minor

#1705 Add tests for export
  src/Datagrid/ProxyQuery.php
  src/Exporter/DataSource.php
  tests/App/Admin/AuthorAdmin.php
  tests/App/Admin/ItemAdmin.php
  tests/App/AppKernel.php
  tests/App/Entity/Author.php
  tests/Datagrid/ProxyQueryTest.php
  tests/Exporter/DataSourceTest.php
  tests/Functional/EmbeddedMappingTest.php
  tests/Functional/ExportActionsTest.php
  tests/Functional/ManyToOneMappingTest.php
Labels: patch

#1739 Drop Symfony 4.4 and Twig 2
  .github/workflows/test-platforms.yaml
  .github/workflows/test.yaml
  composer.json
  src/Resources/config/audit.php
  src/Resources/config/doctrine_orm.php
  src/Resources/config/doctrine_orm_filter_types.php
  src/Resources/config/security.php
  tests/App/AppKernel.php
Labels: minor

#1742 Drop panther ^1
  composer.json
Labels: pedantic

#1745 DevKit updates for 4.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#1747 DevKit updates for 4.x branch
  README.md
Labels: automerge
