Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2023-12, with the labels that each got.

#1780 Allow Symfony 7
  .github/workflows/test.yaml
  composer.json
  src/DependencyInjection/Configuration.php
  tests/App/config/config.yml
Labels: minor

#1781 Release 4.15.0
  CHANGELOG.md
Labels: dev-kit

#1782 DevKit updates for 4.x branch
  rector.php
Labels: automerge, dev-kit

#1783 DevKit updates for 5.x branch
  rector.php
Labels: automerge, dev-kit

#1785 doc(configuration): remove `sonata_doctrine_orm_admin.templates.form` and `sonata_doctrine_orm_admin.templates.filter`
  docs/reference/configuration.rst
Labels: docs

#1786 DevKit updates for 4.x branch
  .php-cs-fixer.dist.php
Labels: automerge, dev-kit

#1787 DevKit updates for 5.x branch
  .php-cs-fixer.dist.php
Labels: automerge, dev-kit
