Repository sonata-project/SonataDoctrineORMAdminBundle, pull requests merged in 2024-04, with the labels that each got.

#1801 Stop using deprecated const
  src/Datagrid/ProxyQuery.php
Labels: pedantic

#1798 DevKit updates for 4.x branch
  .php-cs-fixer.dist.php
Labels: automerge, dev-kit

#1799 DevKit updates for 5.x branch
  .php-cs-fixer.dist.php
Labels: automerge, dev-kit

#1800 Catch possible null value error in ModelFilter
  src/Filter/ModelFilter.php
  tests/Filter/ModelFilterTest.php
Labels: bug

#1802 Pedantic
  tests/Filter/FilterTestCase.php
  tests/Filter/ModelFilterTest.php
Labels: pedantic

#1803 Fix UidFilter
  src/Filter/UidFilter.php
  tests/Filter/UidFilterTest.php
Labels: patch
